#!/usr/bin/env bun
/**
 * Renders the PWA icon PNGs from the SVG sources in `public/icons/`.
 *
 * Sources (committed):
 *   - public/icons/icon.svg          (any-purpose, full visual)
 *   - public/icons/icon-maskable.svg (maskable, content within safe circle)
 *
 * Outputs (also committed, regenerated by `bun run icons:generate`):
 *   - public/icons/icon-192.png            192x192, any-purpose
 *   - public/icons/icon-512.png            512x512, any-purpose
 *   - public/icons/icon-maskable-512.png   512x512, maskable, fully opaque
 *   - public/icons/apple-touch-icon.png    180x180, any-purpose, opaque
 *   - public/apple-touch-icon.png          180x180 — iOS Safari probes /apple-touch-icon.png at the root regardless of <link> tags
 *   - public/apple-touch-icon-precomposed.png 180x180 — same image, satisfies the legacy iOS probe so dev logs and Lighthouse stay clean
 *
 * `sharp` is used for SVG -> PNG rasterization. The package is installed
 * but listed under `ignoreScripts` in package.json — if this script fails
 * with a native-binding error, run `bun install --trust sharp` once.
 */
import sharp from "sharp";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, "..");
const PUBLIC_DIR = join(ROOT, "public");
const ICONS_DIR = join(PUBLIC_DIR, "icons");

type Job = {
  source: string;
  output: string;
  size: number;
  flatten: boolean; // maskable + iOS need fully opaque output
};

const jobs: Job[] = [
  {
    source: join(ICONS_DIR, "icon.svg"),
    output: join(ICONS_DIR, "icon-192.png"),
    size: 192,
    flatten: false,
  },
  {
    source: join(ICONS_DIR, "icon.svg"),
    output: join(ICONS_DIR, "icon-512.png"),
    size: 512,
    flatten: false,
  },
  {
    source: join(ICONS_DIR, "icon-maskable.svg"),
    output: join(ICONS_DIR, "icon-maskable-512.png"),
    size: 512,
    flatten: true, // Android adaptive mask: no transparency
  },
  {
    source: join(ICONS_DIR, "icon.svg"),
    output: join(ICONS_DIR, "apple-touch-icon.png"),
    size: 180,
    flatten: true, // iOS does not honor maskable; keep it opaque
  },
  {
    // iOS Safari probes /apple-touch-icon.png at the root path regardless
    // of <link rel="apple-touch-icon"> hints. Serve it there too to avoid
    // 404 noise in dev logs and Lighthouse PWA audit penalties.
    source: join(ICONS_DIR, "icon.svg"),
    output: join(PUBLIC_DIR, "apple-touch-icon.png"),
    size: 180,
    flatten: true,
  },
  {
    // Legacy probe; same image. iOS dropped the auto-glossy effect in iOS 7
    // but the probe persists for backward compat.
    source: join(ICONS_DIR, "icon.svg"),
    output: join(PUBLIC_DIR, "apple-touch-icon-precomposed.png"),
    size: 180,
    flatten: true,
  },
];

async function render(job: Job): Promise<number> {
  const svg = await readFile(job.source);
  await mkdir(dirname(job.output), { recursive: true });
  let pipeline = sharp(svg, { density: 384 }).resize(job.size, job.size, {
    fit: "contain",
  });
  if (job.flatten) {
    pipeline = pipeline.flatten({ background: "#f6f1e6" });
  }
  const buf = await pipeline.png({ compressionLevel: 9 }).toBuffer();
  await writeFile(job.output, buf);
  return buf.length;
}

async function main() {
  for (const job of jobs) {
    const bytes = await render(job);
    const rel = job.output.replace(`${ROOT}/`, "");
    // eslint-disable-next-line no-console
    console.log(`  ${rel.padEnd(40)} ${job.size}x${job.size}  ${bytes} B`);
  }
}

main().catch((err) => {
  // eslint-disable-next-line no-console
  console.error(err);
  process.exit(1);
});
